language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/steamlink-arduino
  - mv $PWD/examples/SL_bridge0/SL_Credentials.h-sample $PWD/examples/SL_bridge0/SL_Credentials.h
  - arduino --install-library "Adafruit MQTT Library"  
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json,http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards adafruit:samd
  - arduino --install-boards esp8266:esp8266

script:  
  - arduino --verify --board adafruit:samd:feather_m0 $PWD/examples/SL_testclient0/SL_testclient0.ino
  
notifications:
  email:
    on_success: change
    on_failure: change